name: CI-CD # obligatory

on: # the event that needs to be triggered to initiate the workflow automation
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: obtain project code
        uses: actions/checkout@v4
        
      - name: Authenticate in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker Image Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            hbatistuzzo/fake-shop:latest
            hbatistuzzo/fake-shop:v${{github.run_number}}
            
          
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: obtain project code
        uses: actions/checkout@v4
        
      - name: authenticate on AWS
        run: echo "executing the aws configure command"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: configure kubectl
        run: echo "executing aws eks update-kubeconfig command"
      - name: manifest deployment on kubernetes
        run: echo "executing kubectl apply command"
